//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nz.Core.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nz.Core.Model.Validations", typeof(Validations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid offset and size..
        /// </summary>
        public static string ArgumentException_Invalid_offset_and_size {
            get {
                return ResourceManager.GetString("ArgumentException_Invalid_offset_and_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reserve capacity..
        /// </summary>
        public static string ArgumentException_Invalid_reserve_capacity {
            get {
                return ResourceManager.GetString("ArgumentException_Invalid_reserve_capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; cannot be null or blank..
        /// </summary>
        public static string ArgumentIsNullOrWhitespace {
            get {
                return ResourceManager.GetString("ArgumentIsNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of metadata associated with type &apos;{0}&apos; contains the following unknown properties or fields: {1}. Make sure that the names of these members match the names of the properties in the main type..
        /// </summary>
        public static string AssociatedMetadataTypeTypeDescriptor_MetadataTypeContainsUnknownProperties {
            get {
                return ResourceManager.GetString("AssociatedMetadataTypeTypeDescriptor_MetadataTypeContainsUnknownProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; must be public..
        /// </summary>
        public static string AttributeStore_Type_Must_Be_Public {
            get {
                return ResourceManager.GetString("AttributeStore_Type_Must_Be_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not have a public method called &apos;{1}&apos;..
        /// </summary>
        public static string AttributeStore_Unknown_Method {
            get {
                return ResourceManager.GetString("AttributeStore_Unknown_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not have a public property called &apos;{1}&apos;..
        /// </summary>
        public static string AttributeStore_Unknown_Property {
            get {
                return ResourceManager.GetString("AttributeStore_Unknown_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; and &apos;{1}&apos; do not match..
        /// </summary>
        public static string CompareAttribute_MustMatch {
            get {
                return ResourceManager.GetString("CompareAttribute_MustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} was not found..
        /// </summary>
        public static string CompareAttribute_UnknownProperty {
            get {
                return ResourceManager.GetString("CompareAttribute_UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid credit card number..
        /// </summary>
        public static string CreditCardAttribute_Invalid {
            get {
                return ResourceManager.GetString("CreditCardAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; method of type CustomValidationAttribute in type &apos;{1}&apos; must return System.ComponentModel.DataAnnotations.ValidationResult. Use System.ComponentModel.DataAnnotations.ValidationResult.Success to represent success..
        /// </summary>
        public static string CustomValidationAttribute_Method_Must_Return_ValidationResult {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Must_Return_ValidationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; method of type CustomValidationAttribute does not exist in type &apos;{1}&apos; or is not public or static..
        /// </summary>
        public static string CustomValidationAttribute_Method_Not_Found {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomValidationAttribute.Method has not been defined..
        /// </summary>
        public static string CustomValidationAttribute_Method_Required {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{1}&apos; method of type CustomValidationAttribute in type &apos;{1}&apos; must have the signature: public static ValidationResult {0} (object value, ValidationContext context). The value must be a concrete type. The ValidationContext parameter is optional..
        /// </summary>
        public static string CustomValidationAttribute_Method_Signature {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to convert the value of type &apos;{0}&apos; to &apos;{1}&apos; as expected by method {2}. {3}..
        /// </summary>
        public static string CustomValidationAttribute_Type_Conversion_Failed {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Type_Conversion_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom validation type &apos;{0}&apos; must be public..
        /// </summary>
        public static string CustomValidationAttribute_Type_Must_Be_Public {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Type_Must_Be_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} invalid..
        /// </summary>
        public static string CustomValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomValidationAttribute.ValidatorType not informed..
        /// </summary>
        public static string CustomValidationAttribute_ValidatorType_Required {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidatorType_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataType value cannot be null or empty..
        /// </summary>
        public static string DataTypeAttribute_EmptyDataTypeString {
            get {
                return ResourceManager.GetString("DataTypeAttribute_EmptyDataTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for &apos;{0}&apos;..
        /// </summary>
        public static string DataTypeAttribute_InvalidCurrentyValue {
            get {
                return ResourceManager.GetString("DataTypeAttribute_InvalidCurrentyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date {0} must be greater than {1}.
        /// </summary>
        public static string DateGreaterThan_ValidationError {
            get {
                return ResourceManager.GetString("DateGreaterThan_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} property has not been set. Use the {1} method to retrieve the value..
        /// </summary>
        public static string DisplayAttribute_PropertyNotSet {
            get {
                return ResourceManager.GetString("DisplayAttribute_PropertyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} does not have a valid email..
        /// </summary>
        public static string EmailAddressAttribute_Invalid {
            get {
                return ResourceManager.GetString("EmailAddressAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnumDataTypeAttribute cannot be null..
        /// </summary>
        public static string EnumDataTypeAttribute_TypeCannotBeNull {
            get {
                return ResourceManager.GetString("EnumDataTypeAttribute_TypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; must be an enum..
        /// </summary>
        public static string EnumDataTypeAttribute_TypeNeedsToBeAnEnum {
            get {
                return ResourceManager.GetString("EnumDataTypeAttribute_TypeNeedsToBeAnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field accepts only files with the extensions: {1}.
        /// </summary>
        public static string FileExtensionsAttribute_Invalid {
            get {
                return ResourceManager.GetString("FileExtensionsAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; was not recovered due to localization failure. The type &apos;{1}&apos; is not public or does not contain a public static string property with the name &apos;{2}&apos;..
        /// </summary>
        public static string LocalizableString_LocalizationFailed {
            get {
                return ResourceManager.GetString("LocalizableString_LocalizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Length value of MaxLengthAttribute must be greater than zero. Use MaxLength () without parameters to indicate that this string or array can be the maximum size allowed..
        /// </summary>
        public static string MaxLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be a string or array with a maximum size of &apos;{1}&apos;..
        /// </summary>
        public static string MaxLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetadataClassType cannot be null..
        /// </summary>
        public static string MetadataTypeAttribute_TypeCannotBeNull {
            get {
                return ResourceManager.GetString("MetadataTypeAttribute_TypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Length value of MinLengthAttribute must be greater than or equal to zero..
        /// </summary>
        public static string MinLengthAttribute_InvalidMinLength {
            get {
                return ResourceManager.GetString("MinLengthAttribute_InvalidMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be a string or array with a minimum size of &apos;{1}&apos;..
        /// </summary>
        public static string MinLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MinLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field does not have a valid phone..
        /// </summary>
        public static string PhoneAttribute_Invalid {
            get {
                return ResourceManager.GetString("PhoneAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} must implement {1}..
        /// </summary>
        public static string RangeAttribute_ArbitraryTypeNotIComparable {
            get {
                return ResourceManager.GetString("RangeAttribute_ArbitraryTypeNotIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value &apos;{0}&apos; must be greater than or equal to the minimum value &apos;{1}&apos;..
        /// </summary>
        public static string RangeAttribute_MinGreaterThanMax {
            get {
                return ResourceManager.GetString("RangeAttribute_MinGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum and maximum values ​​must be informed..
        /// </summary>
        public static string RangeAttribute_Must_Set_Min_And_Max {
            get {
                return ResourceManager.GetString("RangeAttribute_Must_Set_Min_And_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OperandType must be informed when the minimum and maximum values ​​are strings..
        /// </summary>
        public static string RangeAttribute_Must_Set_Operand_Type {
            get {
                return ResourceManager.GetString("RangeAttribute_Must_Set_Operand_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the {0} field must be between {1} and {2}..
        /// </summary>
        public static string RangeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the field {0} must satisfy the regular expression &apos;{1}&apos;..
        /// </summary>
        public static string RegexAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RegexAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pattern must be a valid regular expression..
        /// </summary>
        public static string RegularExpressionAttribute_Empty_Pattern {
            get {
                return ResourceManager.GetString("RegularExpressionAttribute_Empty_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is mandatory..
        /// </summary>
        public static string RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum size must be a positive integer.
        /// </summary>
        public static string StringLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("StringLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the {0} field must be a string with a maximum length of {1}..
        /// </summary>
        public static string StringLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be a text with a minimum of {2} and a maximum of {1} characters..
        /// </summary>
        public static string StringLengthAttribute_ValidationErrorIncludingMinimum {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationErrorIncludingMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field value is not a valid http, https, or ftp URL..
        /// </summary>
        public static string UrlAttribute_Invalid {
            get {
                return ResourceManager.GetString("UrlAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of ErrorMessageString or ErrorMessageResourceName must be defined, but not both..
        /// </summary>
        public static string ValidationAttribute_Cannot_Set_ErrorMessage_And_Resource {
            get {
                return ResourceManager.GetString("ValidationAttribute_Cannot_Set_ErrorMessage_And_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsValid (object value) was not implemented in this class. The preferred method is GetValidationResult () and the class must override IsValid (object value, ValidationContext context)..
        /// </summary>
        public static string ValidationAttribute_IsValid_NotImplemented {
            get {
                return ResourceManager.GetString("ValidationAttribute_IsValid_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both ErrorMessageResourceType and ErrorMessageResourceName must be entered in this attribute..
        /// </summary>
        public static string ValidationAttribute_NeedBothResourceTypeAndResourceName {
            get {
                return ResourceManager.GetString("ValidationAttribute_NeedBothResourceTypeAndResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; in the resource of type &apos;{1}&apos; is not a string..
        /// </summary>
        public static string ValidationAttribute_ResourcePropertyNotStringType {
            get {
                return ResourceManager.GetString("ValidationAttribute_ResourcePropertyNotStringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource of type &apos;{0}&apos; does not have a static property with the name &apos;{1}&apos;..
        /// </summary>
        public static string ValidationAttribute_ResourceTypeDoesNotHaveProperty {
            get {
                return ResourceManager.GetString("ValidationAttribute_ResourceTypeDoesNotHaveProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field value is invalid..
        /// </summary>
        public static string ValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("ValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidationContext for type &apos;{0}&apos;, member &apos;{1}&apos; must have MethodInfo..
        /// </summary>
        public static string ValidationContext_Must_Be_Method {
            get {
                return ResourceManager.GetString("ValidationContext_Must_Be_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service of type &apos;{0}&apos; already exists in the container..
        /// </summary>
        public static string ValidationContextServiceContainer_ItemAlreadyExists {
            get {
                return ResourceManager.GetString("ValidationContextServiceContainer_ItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied instance must be of type ObjectInstance in the supplied ValidationContext..
        /// </summary>
        public static string Validator_InstanceMustMatchValidationContextInstance {
            get {
                return ResourceManager.GetString("Validator_InstanceMustMatchValidationContextInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the property &apos;{0}&apos; must be of type &apos;{1}&apos;..
        /// </summary>
        public static string Validator_Property_Value_Wrong_Type {
            get {
                return ResourceManager.GetString("Validator_Property_Value_Wrong_Type", resourceCulture);
            }
        }
    }
}
