//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nz.Libs.MessageTemplate.Impl.MessageResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nz.Libs.MessageTemplate.Impl.MessageResource.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {FirstName} your password has been changed, use your email {Email} to access the site..
        /// </summary>
        public static string MessageTemplateType_EmailChangePassword {
            get {
                return ResourceManager.GetString("MessageTemplateType_EmailChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {FirstName}, your new password has been saved. Use your email {Email} to access the site..
        /// </summary>
        public static string MessageTemplateType_EmailConfirmForgotPassword {
            get {
                return ResourceManager.GetString("MessageTemplateType_EmailConfirmForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {FirstName}, your account has been verified. Use your email {Email} to access the site..
        /// </summary>
        public static string MessageTemplateType_EmailConfirmNewUserRegister {
            get {
                return ResourceManager.GetString("MessageTemplateType_EmailConfirmNewUserRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {FirstName}, use the code {RecoveryPasswordToken} to recover your password..
        /// </summary>
        public static string MessageTemplateType_EmailForgotPassword {
            get {
                return ResourceManager.GetString("MessageTemplateType_EmailForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {FirstName}, welcome! Your confirmation code is: {ConfirmationToken}.
        /// </summary>
        public static string MessageTemplateType_EmailNewUserRegister {
            get {
                return ResourceManager.GetString("MessageTemplateType_EmailNewUserRegister", resourceCulture);
            }
        }
    }
}
